repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.15.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.0"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args:
          - "--sp"
          - "app/pyproject.toml"
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - "--config=./app/.flake8"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "django-stubs"
        entry: bash -c 'cd app && mypy --config pyproject.toml .' --
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    - id: bandit
      args:
        - "-c"
        - "app/pyproject.toml"
        - "-r"
        - "app/"
      additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
