site_name: django-scaffold

docs_dir: docs

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight

plugins:
  - search:

nav:
  - Index Page: index.md
  - Tutorials: tutorials.md
  - How-To-Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

# to navigate with `/site` content correctly
use_directory_urls: false
