[tool.bandit]
exclude_dirs = ["venv"]
targets = "app"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "project.settings"
